apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-boot
spec:
  replicas: 2
  selector:
    app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot-pod
        image: systane/kubernetes:latest
        ports:
        -  containerPort: 8081