apiVersion: v1
kind: Service
metadata:
  name: spring-boot-svc
  labels:
    app: spring-boot
spec:
  type: NodePort
  ports:
  - port: 8081
    nodePort: 30001
    protocol: TCP
  selector:
    app: spring-boot