version: '2.1'
services:
  config-server:
    build:
      dockerfile: ./config-server/Dockerfile
      context: .
    container_name: configServerContainer
    ports:
      - "9090:9090"
    # healthcheck:
    #   test: ./health.sh
    #   interval: 60s
    #   timeout: 10s
    #   retries: 2
  
  eureka-server:
    build:
      dockerfile: ./eureka-server/Dockerfile
      context: .
    container_name: eurekaServerContainer
    ports:
      - "9091:9091"
    # depends_on:
    #   config-server:
    #     condition: service_healthy

# ======================= ORDER DOS CONTAINERS FUNCIONANDO ===============================
# version: '2.1'
# services:
#   config-server:
#     build:
#       dockerfile: ./config-server/Dockerfile
#       context: .
#     container_name: configServerContainer
#     ports:
#       - "9090:9090"
#     healthcheck:
#       test: ./health.sh
#       interval: 60s
#       timeout: 10s
#       retries: 2
  
#   eureka-server:
#     build:
#       dockerfile: ./eureka-server/Dockerfile
#       context: .
#     container_name: eurekaServerContainer
#     ports:
#       - "9091:9091"
#     depends_on:
#       config-server:
#         condition: service_healthy
#======================================================================



# ======================  COMPOSING OTHER CONTAINERS ============================
  # auth-server:
  #   build:
  #     dockerfile: ./auth-server/Dockerfile
  #     context: .
  #   container_name: auth_server_container
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - "config-server"
  #     - "eureka-server"

  # order-service:
  #   build:
  #     dockerfile: ./order-service/Dockerfile
  #     context: .
  #   container_name: order_server_container
  #   ports:
  #     - "9093:9093"
  #   depends_on:
  #     - "config-server"
  #     - "eureka-server"
  #     - "auth-server"