#Configurações que que serão substituidas no starter do Spring boot

server:
  port: 9090

  spring:
    cloud:
      config:
        server:
          git:
            uri:https://github.com/systane/courses/tree/master/springCloud/config-files